### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by hack-scan** [lavague-ai/LaVague#106]
ERROR: Project file:///home/scan/Desktop/LaVague-main/LaVague/LaVague has a 'pyproject.toml' and its build backend is missing the 'build_editable' hook. Since it does not have a 'setup.py' nor a 'setup.cfg', it cannot be installed in editable mode. Consider using a build backend that supports PEP 660.

**Comment by lyie28** [comment]
Have you tried upgrading pip? Usually you can run pip install -e with just a pyproject.toml with the latest version of pip: 

python3 -m pip install --upgrade pip

**Comment by hack-scan** [comment]
![image](https://github.com/lavague-ai/LaVague/assets/36232689/1fe03590-bcbe-40d7-9aaa-d859e2da9b71)
![image](https://github.com/lavague-ai/LaVague/assets/36232689/aff12622-6d39-45a6-945c-4b1b6772853f)
Thank you very much for your reply. I have tried to update the pip, but there is currently no solution

**Comment by hack-scan** [comment]
Since it does not have a 'setup.py' nor a 'setup.cfg'

**Comment by lyie28** [comment]
If you just want to run the solution without playing with modifying the source code, you can just remove the '-e' option from the pip install in the script. I was planning to change it to 'pip install lavague' anyway

**Comment by hack-scan** [comment]
That's great. Installation with pip is much more convenient. Thank you author for your hard work!

**Comment by hack-scan** [comment]
![image](https://github.com/lavague-ai/LaVague/assets/36232689/d320317a-1e4e-4c4d-9402-5d432408bf00)
Is it because I didn't install it correctly?

**Comment by hack-scan** [comment]
`scan@scan-virtual-machine:~/Desktop/new_lav$ lavague-launch --file_path tests/hf.txt --config_file examples/api/openai_api.py
Traceback (most recent call last):
  File "/home/scan/.local/bin/lavague-launch", line 5, in <module>
    from lavague import launch
  File "/home/scan/Desktop/new_lav/LaVague/src/lavague/__init__.py", line 3, in <module>
    from .command_center import GradioDemo
  File "/home/scan/Desktop/new_lav/LaVague/src/lavague/command_center.py", line 3, in <module>
    import gradio as gr
  File "/home/scan/.local/lib/python3.10/site-packages/gradio/__init__.py", line 3, in <module>
    import gradio._simple_templates
  File "/home/scan/.local/lib/python3.10/site-packages/gradio/_simple_templates/__init__.py", line 1, in <module>
    from .simpledropdown import SimpleDropdown
  File "/home/scan/.local/lib/python3.10/site-packages/gradio/_simple_templates/simpledropdown.py", line 6, in <module>
    from gradio.components.base import FormComponent
  File "/home/scan/.local/lib/python3.10/site-packages/gradio/components/__init__.py", line 1, in <module>
    from gradio.components.annotated_image import AnnotatedImage
  File "/home/scan/.local/lib/python3.10/site-packages/gradio/components/annotated_image.py", line 14, in <module>
    from gradio.components.base import Component
  File "/home/scan/.local/lib/python3.10/site-packages/gradio/components/base.py", line 20, in <module>
    from gradio.blocks import Block, BlockContext
  File "/home/scan/.local/lib/python3.10/site-packages/gradio/blocks.py", line 29, in <module>
    from gradio import (
  File "/home/scan/.local/lib/python3.10/site-packages/gradio/networking.py", line 20, in <module>
    from gradio.routes import App
  File "/home/scan/.local/lib/python3.10/site-packages/gradio/routes.py", line 136, in <module>
    client = httpx.AsyncClient()
  File "/home/scan/.local/lib/python3.10/site-packages/httpx/_client.py", line 1429, in __init__
    proxy_map = self._get_proxy_map(proxies or proxy, allow_env_proxies)
  File "/home/scan/.local/lib/python3.10/site-packages/httpx/_client.py", line 217, in _get_proxy_map
    return {
  File "/home/scan/.local/lib/python3.10/site-packages/httpx/_client.py", line 218, in <dictcomp>
    key: None if url is None else Proxy(url=url)
  File "/home/scan/.local/lib/python3.10/site-packages/httpx/_config.py", line 336, in __init__
    raise ValueError(f"Unknown scheme for proxy URL {url!r}")
ValueError: Unknown scheme for proxy URL URL('socks://127.0.0.1:7897/')
`
安装完成后又这样报错

**Comment by hack-scan** [comment]
Already solved, thank you
