### ISSUE TITLE
Getting a OSError: [WinError 193] %1 is not a valid Win32 application error when trying to get started with the project

### ISSUE THREAD

**Issue by aganchev1** [lavague-ai/LaVague#154]
**Describe the bug**
I am unable the work with the starter commands due to a `OSError: [WinError 193] %1 is not a valid Win32 application error. `

**To Reproduce**
1. Download the project files via setup.sh
2. Create a new Python 3.10 environment due to bug reported here ([issue 151](https://github.com/lavague-ai/LaVague/issues/151))
3. Install LaVague via pip install
4. Install requirements.txt from docs/
5. Run starter command `lavague --instructions examples/instructions/huggingface.yaml --config examples/configurations/api/openai_api.py launch`

**Other info**
I'm able to operate Selenium just fine outside of this and I've made sure there are no environment funnies (I think).

Any help/thoughts appreciated. Perhaps I've missed a step somewhere?

**Full Error**
`(python310) C:\Users\AngelGanchev\PycharmProjects\ResearchProjects\RR\tech setup\LaVague>lavague --instructions examples/instructions/huggingface.yaml --config examples/configurations/api/openai_api.py launch
Traceback (most recent call last):
  File "C:\Users\AngelGanchev\miniconda3\envs\python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\AngelGanchev\miniconda3\envs\python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\AngelGanchev\miniconda3\envs\python310\Scripts\lavague.exe\__main__.py", line 7, in <module>
    sys.exit(cli())
  File "C:\Users\AngelGanchev\miniconda3\envs\python310\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\AngelGanchev\miniconda3\envs\python310\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\Users\AngelGanchev\miniconda3\envs\python310\lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\AngelGanchev\miniconda3\envs\python310\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\AngelGanchev\miniconda3\envs\python310\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\AngelGanchev\miniconda3\envs\python310\lib\site-packages\click\decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\Users\AngelGanchev\miniconda3\envs\python310\lib\site-packages\lavague\cli\commands.py", line 21, in launch
    driver = config.get_driver()
  File "C:\Users\AngelGanchev\miniconda3\envs\python310\lib\site-packages\lavague\defaults.py", line 92, in default_get_selenium_driver
    driver = webdriver.Chrome(service=webdriver_service, options=chrome_options)
  File "C:\Users\AngelGanchev\miniconda3\envs\python310\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 45, in __init__
    super().__init__(
  File "C:\Users\AngelGanchev\miniconda3\envs\python310\lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 50, in __init__
    self.service.start()
  File "C:\Users\AngelGanchev\miniconda3\envs\python310\lib\site-packages\selenium\webdriver\common\service.py", line 98, in start
    self._start_process(self._path)
  File "C:\Users\AngelGanchev\miniconda3\envs\python310\lib\site-packages\selenium\webdriver\common\service.py", line 208, in _start_process
    self.process = subprocess.Popen(
  File "C:\Users\AngelGanchev\miniconda3\envs\python310\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\AngelGanchev\miniconda3\envs\python310\lib\subprocess.py", line 1456, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
OSError: [WinError 193] %1 is not a valid Win32 application`

**Comment by lyie28** [comment]
Hi there, `setup.sh` is designed for Linux only, not Windows. We haven't yet created a Windows-specific startup script, but I can look into doing this (but I might not have time until next week) - or if you'd like to contribute one, we'd be happy to integrate your work :)

If you have docker installed, you could use the Docker option instead:
https://docs.lavague.ai/en/latest/docs/get-started/setting-up-la-vague/#docker-setup

The `setup.sh` script just installs the correct webdriver & Chrome binary for Linux (Debian derivatives) to our default Linux location. Then in `defaults.py` we have the default paths defined which is what LaVague will use as the path for these files - we have a default macos and Linux path but not Windows, so in your case, this path will be incorrect. You would need to change these paths and then install the package from your locally modified version of the package to get this to work.

**Comment by lyie28** [comment]
Also I just fixed the python3.8 bug - fix is in version 1.0.8 :)

**Comment by aganchev1** [comment]
many thanks for the prompt reply, will try the docker route for now!
