### ISSUE TITLE
playwright._impl._errors.Error

### ISSUE THREAD

**Issue by agn-7** [lavague-ai/LaVague#206]
The day before yesterday, I could run the project and open google or huggingface website and input prompt to generate the respective web interaction properly via google colab example. But today I got the `playwright` installation error:

So I added a new cell as follows to fix the issue:

```bash
playwright install
```

Now, I get the following error when I enter a website to be opened:

```bash
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/queueing.py", line 501, in call_prediction
    output = await route_utils.call_process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/route_utils.py", line 253, in call_process_api
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1695, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1235, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 692, in wrapper
    response = f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/lavague/command_center.py", line 48, in init_driver_impl
    driver = self.get_driver()
  File "/usr/local/lib/python3.10/dist-packages/lavague/defaults.py", line 156, in default_get_playwright_driver
    p = sync_playwright().start()
  File "/usr/local/lib/python3.10/dist-packages/playwright/sync_api/_context_manager.py", line 85, in start
    return self.__enter__()
  File "/usr/local/lib/python3.10/dist-packages/playwright/sync_api/_context_manager.py", line 48, in __enter__
    raise Error(
playwright._impl._errors.Error: It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.
```

**Comment by lyie28** [comment]
Hi @agn-7,

Thanks for flagging this. 

We were hoping to make Playwright out default driver instead of Selenium, but quickly realized that it's async nature made the implementation quite problematic in Google Colabs and for our Gradio launch command, so we've gone back to Selenium! 

If you try using the package now with the latest version, you shouldn't have this issue now as we are back to Selenium by default!
