### ISSUE TITLE
LaVague crashed after starting Navigation Controls at SCAN instruction

### ISSUE THREAD

**Issue by danielkornev** [lavague-ai/LaVague#279]
**Describe the bug**
Asked the system to get founders' names from a website (e.g., induced.ai). Expected it to get the list but system crashed.

**To Reproduce**
1. Use Windows 11 24H2, Python 3.10 (installed via WinGet) natively (e.g., non-WSL)
2. Use Terminal
1. Install LaVague via pip
3. Create file test.py and write this code in it:
```
from lavague.core import  WorldModel, ActionEngine
from lavague.core.agents import WebAgent
from lavague.drivers.selenium import SeleniumDriver

selenium_driver = SeleniumDriver(headless=False)
world_model = WorldModel()
action_engine = ActionEngine(selenium_driver)
agent = WebAgent(world_model, action_engine)
agent.get("https://www.induced.ai")
agent.run("Give me a list of founders of the company")
```

5. Run the program (python test.py)
6. See error

**Expected behavior**
An answer with the list of founders' names.

**Terminal Output**

```
Traceback (most recent call last):
  File "C:\stuff\dev\exp-lavague\test.py", line 15, in <module>
    agent.run("Give me a list of founders of the company")
  File "C:\Users\danie\AppData\Local\Programs\Python\Python310\lib\site-packages\lavague\core\agents.py", line 84, in run
    success, output = self.action_engine.dispatch_instruction(
  File "C:\Users\danie\AppData\Local\Programs\Python\Python310\lib\site-packages\lavague\core\action_engine.py", line 230, in dispatch_instruction
    return next_engine.execute_instruction(instruction)
  File "C:\Users\danie\AppData\Local\Programs\Python\Python310\lib\site-packages\lavague\core\navigation.py", line 60, in execute_instruction
    exec(code, local_scope, local_scope)
  File "<string>", line 1, in <module>
  File "C:\Users\danie\AppData\Local\Programs\Python\Python310\lib\site-packages\lavague\drivers\selenium\base.py", line 138, in get_screenshots_whole_page
    if self.is_bottom_of_page():
  File "C:\Users\danie\AppData\Local\Programs\Python\Python310\lib\site-packages\lavague\drivers\selenium\base.py", line 109, in is_bottom_of_page
    return self.driver.execute_script(
  File "C:\Users\danie\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 407, in execute_script
    return self.execute(command, {"script": script, "args": converted_args})["value"]
  File "C:\Users\danie\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\danie\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: disconnected: unable to send message to renderer
  (failed to check if window was closed: disconnected: not connected to DevTools)
  (Session info: chrome=125.0.6422.78)
Stacktrace:
        GetHandleVerifier [0x00007FF6CF1A1F22+60322]
        (No symbol) [0x00007FF6CF11CE99]
        (No symbol) [0x00007FF6CEFD7EBA]
        (No symbol) [0x00007FF6CEFBF79C]
        (No symbol) [0x00007FF6CEFBF70C]
        (No symbol) [0x00007FF6CEFBDEFC]
        (No symbol) [0x00007FF6CEFBEBAF]
        (No symbol) [0x00007FF6CEFDBAAF]
        (No symbol) [0x00007FF6CEFDC5D3]
        (No symbol) [0x00007FF6CEFE0968]
        (No symbol) [0x00007FF6CF06C95B]
        (No symbol) [0x00007FF6CF04C21A]
        (No symbol) [0x00007FF6CF06BC80]
        (No symbol) [0x00007FF6CF04BFC3]
        (No symbol) [0x00007FF6CF019617]
        (No symbol) [0x00007FF6CF01A211]
        GetHandleVerifier [0x00007FF6CF4B946D+3301613]
        GetHandleVerifier [0x00007FF6CF503693+3605267]
        GetHandleVerifier [0x00007FF6CF4F9410+3563664]
        GetHandleVerifier [0x00007FF6CF2542F6+790390]
        (No symbol) [0x00007FF6CF1274DF]
        (No symbol) [0x00007FF6CF1233D4]
        (No symbol) [0x00007FF6CF123562]
        (No symbol) [0x00007FF6CF112F6F]
        BaseThreadInitThunk [0x00007FF92C471FD7+23]
        RtlUserThreadStart [0x00007FF92D09B66C+44]

PS C:\stuff\dev\exp-lavague> [48488:41816:0529/121631.892:ERROR:device_event_log_impl.cc(195)] [12:16:31.631] USB: usb_service_win.cc:105 SetupDiGetDeviceProperty({{A45C254E-DF1C-4EFD-8020-67D146A850E0}, 6}) failed: Element not found. (0x490)
[48488:41816:0529/121633.189:ERROR:device_event_log_impl.cc(195)] [12:16:33.181] USB: usb_service_win.cc:105 SetupDiGetDeviceProperty({{A45C254E-DF1C-4EFD-8020-67D146A850E0}, 6}) failed: Element not found. (0x490)
```

**Comment by lyie28** [comment]
Hi @danielkornev - seems like the webdriver lost connection with the browser/ it crashed.

Can you tell me what your set-up is? Linux? WSL? Mac? Google Colab?

**Comment by danielkornev** [comment]
Hi Laura,

Windows 11, amd64, 24H2, non-WSL, Python 3.10. Running a program from terminal (wrote it using VS Code).

**Comment by lyie28** [comment]
Hi again @danielkornev,

Could you check that your version of chromedriver is compatible with your version of chrome:

I believe you can run this: `chromedriver --version` in command prompt which should output:
ChromeDriver XX.XXX.XX (matching Chrome browser version XX)

Then you can check the version of your Chrome browser version to check it is compatible with the driver, by running (modify if the path is wrong):
`"C:\Program Files\Google\Chrome\Application\chrome.exe" --version`

If that looks fine, can you let me know what versions you are using in any case.

Also, if you switch to `headless=True` in your original code - does that fix the webdriver crash problem?

**Comment by danielkornev** [comment]
Version 125.0.6422.114 (Official Build) (64-bit)

**Comment by lyie28** [comment]
@danielkornev Are you using a VM? If so, I think it will at least work in headless mode:

```python
from lavague.core import  WorldModel, ActionEngine
from lavague.core.agents import WebAgent
from lavague.drivers.selenium import SeleniumDriver

selenium_driver = SeleniumDriver(headless=True)
world_model = WorldModel()
action_engine = ActionEngine(selenium_driver)
agent = WebAgent(world_model, action_engine)
agent.get("https://huggingface.co/")
agent.run("Give me the name of the top model")
```

Does it work for you?

I plan to create some comprehensive guide on solving issues around non-headless mode for browser-less this week so I'll get back to you for non-headless mode.

**Comment by lyie28** [comment]
Hey, will close due to inactivity but feel free to ping us on Discord or re-open an issue if you are still having issues.
