### ISSUE TITLE
Playwright Driver  raise error AttributeError: 'BrowserContext' object has no attribute 'new_context'

### ISSUE THREAD

**Issue by rmrf** [lavague-ai/LaVague#448]
**Describe the bug**
Playwright Driver  raise error AttributeError: 'BrowserContext' object has no attribute 'new_context'

**To Reproduce**

code below works fine when using SeleniumDriver, but PlaywrightDriver would raise error.
I had try on two different computers, and with python 3.10, 3.12, raise same error. 

```
from lavague.drivers.selenium import SeleniumDriver
from lavague.drivers.playwright import PlaywrightDriver

...
# Initialize context with our custom elements
context = Context(llm, mm_llm, embedding)

# Initialize the Selenium driver
# driver = SeleniumDriver(headless=False, user_data_dir='/home/rmrf/Chrome/debug11')
driver = PlaywrightDriver(headless=False, user_data_dir='/home/rmrf/Chrome/debug11')

# Initialize a WorldModel and ActionEnginem passing them the custom context
world_model = WorldModel.from_context(context)
action_engine = ActionEngine.from_context(context, driver)

# Create your agent
agent = WebAgent(world_model, action_engine)

agent.get(url)
agent.run(target)

```

**Expected behavior**
same as SeleniumDriver

**Screenshots**
```
Traceback (most recent call last):
  File "/home/rmrf/Github/rmrf/Voiture/scratch/./wenjuan_test.py", line 70, in <module>
    driver = PlaywrightDriver(headless=False, user_data_dir='/home/ycqian/Chrome/debug11')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rmrf/miniconda3/envs/lavague12/lib/python3.12/site-packages/lavague/drivers/playwright/base.py", line 35, in __init__
    super().__init__(url, get_sync_playwright_page)
  File "/home/rmrf/miniconda3/envs/lavague12/lib/python3.12/site-packages/lavague/core/base_driver.py", line 31, in __init__
    self.driver = self.init_function()
                  ^^^^^^^^^^^^^^^^^^^^
  File "/home/rmrf/miniconda3/envs/lavague12/lib/python3.12/site-packages/lavague/drivers/playwright/base.py", line 70, in default_init_code
    context = browser.new_context(user_agent=user_agent)
              ^^^^^^^^^^^^^^^^^^^
AttributeError: 'BrowserContext' object has no attribute 'new_context'

**Comment by adeprez** [comment]
Hello,
Is your playwright up to date with chromium engine installed?
```
pip install playwright
playwright install chromium
```

**Comment by rmrf** [comment]
@adeprez yes, I have already install the chromium engine, I have tested with bellow playwright code:
```python
from playwright.sync_api import sync_playwright
import time

playwright = sync_playwright().start()
browser = playwright.chromium.launch(headless=False)
page = browser.new_page()
page.goto("https://vercel.com/")
print(page.title())
time.sleep(10)
browser.close()
playwright.stop()

**Comment by rmrf** [comment]
SeleniumDriver is not the first choice, as each time started SeleniumDriver tries to connect to an ip of Github(tcpdump show that). I have no idea how to disable this.  This connection slows down my whole running process inside our corp network. 

but PlaywrightDriver is very clean, no outside connection spots out, so I really wish playwright could work during my test.

**Comment by adeprez** [comment]
Can you share the output of this command:
```bash
pip show playwright
```

It looks like the [new_context](https://playwright.dev/python/docs/api/class-browser#browser-new-context) method is missing for you. I was added in playwright 1.8, and LaVague uses playwright 1.42.0+

**Comment by rmrf** [comment]
seems version enough.

```
❯ pip show playwright
Name: playwright
Version: 1.45.0
Summary: A high-level API to automate web browsers
Home-page: https://github.com/Microsoft/playwright-python
Author: Microsoft Corporation
Author-email: 
License: Apache-2.0
Location: /home/rmrf/miniconda3/envs/lavague12/lib/python3.12/site-packages
Requires: greenlet, pyee
Required-by: lavague-drivers-playwright

➜ pip show lavague
Name: lavague
Version: 1.1.10
Summary: automation code generation from text instructions
Home-page: https://mithrilsecurity.io
Author: lavague-ai
Author-email: 
License: Apache-2.0
Location: /home/rmrf/miniconda3/envs/lavague12/lib/python3.12/site-packages
Requires: lavague-contexts-openai, lavague-core, lavague-drivers-selenium, lavague-gradio
Required-by:

**Comment by adeprez** [comment]
It appears that the Playwright driver isn't initializing correctly when `user_data_dir` is supplied. I will push a fix soon. Thank you for identifying the issue, your bug report is much appreciated!

**Comment by adeprez** [comment]
Fixed in `lavague-drivers-playwright` version `0.2.10`

**Comment by rmrf** [comment]
Thanks @adeprez , it works now!
