### ISSUE TITLE
Notion example currently broken because wait() in base_driver.py passes invalid data structure that selenium exec_code() does not expect

### ISSUE THREAD

**Issue by tm-robinson** [lavague-ai/LaVague#459]
**Describe the bug**
When trying to run the Notion example from the documentation on the latest version of LaVague from pip, the following error is given:

```
(venv) tom@lenovo:~/development/lavague-test$ python notion_qa.py 
/home/tom/development/lavague-test/venv/lib/python3.10/site-packages/lavague/__init__.py:10: UserWarning: Telemetry is turned on. To turn off telemetry, set your TELEMETRY_VAR to 'NONE'
  warnings.warn(warning_message, UserWarning)
/home/tom/development/lavague-test/venv/lib/python3.10/site-packages/lavague/__init__.py:16: UserWarning: Security warning: This package executes LLM-generated code. Consider using this package in a sandboxed environment.
  warnings.warn(warning_message, UserWarning)
/home/tom/development/lavague-test/venv/lib/python3.10/site-packages/lavague/core/__init__.py:21: UserWarning: Telemetry is turned on. To turn off telemetry, set your LAVAGUE_TELEMETRY to 'NONE'
  warnings.warn(warning_message, UserWarning)
2024-07-21 08:09:51,148 - INFO - Screenshot folder cleared
2024-07-21 08:09:55,301 - INFO - Thoughts:
- The current screenshot shows a loading screen for Notion.
- The objective is to find the name of the Lead Developer.
- Since the page is still loading, we need to wait for it to fully load before proceeding.

Next engine: Navigation Controls
Instruction: WAIT 5
2024-07-21 08:09:55,307 - ERROR - Error while running the agent: 'action'
Traceback (most recent call last):
  File "/home/tom/development/lavague-test/notion_qa.py", line 10, in <module>
    agent.run("What's the name of our Lead Developer ?")
  File "/home/tom/development/lavague-test/venv/lib/python3.10/site-packages/lavague/core/agents.py", line 341, in run
    raise e
  File "/home/tom/development/lavague-test/venv/lib/python3.10/site-packages/lavague/core/agents.py", line 328, in run
    result = self.run_step(objective)
  File "/home/tom/development/lavague-test/venv/lib/python3.10/site-packages/lavague/core/agents.py", line 295, in run_step
    action_result = self.action_engine.dispatch_instruction(
  File "/home/tom/development/lavague-test/venv/lib/python3.10/site-packages/lavague/core/action_engine.py", line 223, in dispatch_instruction
    return next_engine.execute_instruction(instruction)
  File "/home/tom/development/lavague-test/venv/lib/python3.10/site-packages/lavague/core/navigation.py", line 567, in execute_instruction
    self.driver.wait(self.time_between_actions)
  File "/home/tom/development/lavague-test/venv/lib/python3.10/site-packages/lavague/core/base_driver.py", line 288, in wait
    self.exec_code(code)
  File "/home/tom/development/lavague-test/venv/lib/python3.10/site-packages/lavague/drivers/selenium/base.py", line 252, in exec_code
    action_name = action["action"]["name"]
KeyError: 'action'
```

**To Reproduce**
1. Install the latest version from pip
2. Create a python file and paste in the code from https://docs.lavague.ai/en/latest/docs/use-cases/notion/
3. Run the file
4. Error above appears

**Expected behavior**
Notion example should execute correctly.

**Updated Code**

Within `base_driver.py` the `wait()` function needs to be updated to read:

```
    def wait(self, duration):
        import json

        code = json.dumps(
            [
                {
                    "actions": [ 
                        { 
                            "action": {
                                "name": "wait",
                                "args": {
                                    "duration": duration,
                                },
                            } 
                        } 
                    ]
                }
            ]
        )
        self.exec_code(code)
```

**Complete code**
This is the code I used for the Notion example.  NB I had to add `, ActionEngine` to the end of the first line.

```
from lavague.core import WebAgent, WorldModel, ActionEngine
from lavague.drivers.selenium import SeleniumDriver

selenium_driver = SeleniumDriver()
action_engine = ActionEngine(selenium_driver)
world_model = WorldModel()
agent = WebAgent(world_model, action_engine)

agent.get("https://maize-paddleboat-93e.notion.site/Welcome-to-ACME-INC-0ac66cd290e3453b93a993e1a3ed272f")
agent.run("What's the name of our Lead Developer ?")
```

**Output after the above change to `base_driver.py`**
```
(venv) tom@lenovo:~/development/lavague-test$ python notion_qa.py 
/home/tom/development/lavague-test/venv/lib/python3.10/site-packages/lavague/__init__.py:10: UserWarning: Telemetry is turned on. To turn off telemetry, set your TELEMETRY_VAR to 'NONE'
  warnings.warn(warning_message, UserWarning)
/home/tom/development/lavague-test/venv/lib/python3.10/site-packages/lavague/__init__.py:16: UserWarning: Security warning: This package executes LLM-generated code. Consider using this package in a sandboxed environment.
  warnings.warn(warning_message, UserWarning)
/home/tom/development/lavague-test/venv/lib/python3.10/site-packages/lavague/core/__init__.py:21: UserWarning: Telemetry is turned on. To turn off telemetry, set your LAVAGUE_TELEMETRY to 'NONE'
  warnings.warn(warning_message, UserWarning)
2024-07-21 08:11:08,724 - INFO - Screenshot folder cleared
2024-07-21 08:11:12,995 - INFO - Thoughts:
- The current screenshot shows a loading screen for a Notion workspace.
- The objective is to find the name of the Lead Developer.
- Since the page is still loading, we need to wait for it to fully load before proceeding.

Next engine: Navigation Controls
Instruction: WAIT 5
2024-07-21 08:11:17,542 - INFO - Thoughts:
- The current screenshot shows the welcome page of ACME INC.
- The objective is to find the name of the Lead Developer.
- The page contains sections about the company, services, departments, and contact information.
- The information about the Lead Developer is likely to be found under the 'Our Departments' section, specifically in the 'Software Development' department.

Next engine: Navigation Engine
Instruction: Click on the 'Software Development' link under the 'Our Departments' section.
2024-07-21 08:11:27,669 - INFO - Thoughts:
- The current screenshot shows the 'Software Development' page of ACME INC.
- The objective is to find the name of the Lead Developer.
- The page lists various teams under the Software Development department, but does not directly mention the Lead Developer.
- The next step should involve exploring the 'Software Development Team Information' link, as it is likely to contain details about the team members, including the Lead Developer.

Next engine: Navigation Engine
Instruction: Click on the 'Software Development Team Information' link.
2024-07-21 08:11:38,105 - INFO - Thoughts:
- The current screenshot shows the 'Software Development Team Information' page.
- The objective is to find the name of the Lead Developer.
- The information about the team members is clearly listed on the page.
- The name of the Lead Developer is mentioned as 'Mike Patel'.

Next engine: COMPLETE
Instruction: The name of the Lead Developer is Mike Patel.
2024-07-21 08:11:38,105 - INFO - Objective reached. Stopping...
```

**Comment by JoFrost** [comment]
Hi @tm-robinson! This issue has been fixed. Please pull the last version of lavague-core.
