### ISSUE TITLE
avague-launch --file_path hf.txt  --config_path openai.py

### ISSUE THREAD

**Issue by serdarkaracay** [lavague-ai/LaVague#82]
Hello folks,
I'm trying to get the project off its feet with the source code.
I gave the file path in the lavague launch command parameters, this did not work.
I tried the commands in the normal document.

I started with the setup.sh file, there was no error here.
Chrome driver unzip was done successfully.
I am working in a virtual environment with conda.

There's openai.py file on path lavague-files and examples/api 

When the command tried on those paths, chromedriver error. 

```shell
 lavague-launch --file_path hf.txt  --config_path openai.py                                                                                                                    
Traceback (most recent call last):
  File "/opt/anaconda3/envs/LaVague/bin/lavague-launch", line 8, in <module>
    sys.exit(launch())
  File "/Users/serdarkaracay/AiWebScraby/LaVague/src/lavague/__init__.py", line 121, in launch
    action_engine, get_driver = load_action_engine(config_path, streaming=True)
  File "/Users/serdarkaracay/AiWebScraby/LaVague/src/lavague/utils.py", line 18, in load_action_engine
    config_module = import_from_path(path)
  File "/Users/serdarkaracay/AiWebScraby/LaVague/src/lavague/utils.py", line 13, in import_from_path
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 982, in get_code
  File "<frozen importlib._bootstrap_external>", line 1039, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'openai.py'
(LaVague) 
```

```shell
LaVague 
❯ conda info

     active environment : LaVague
    active env location : /opt/anaconda3/envs/LaVague
            shell level : 5
       user config file : /Users/serdarkaracay/.condarc
 populated config files : /Users/serdarkaracay/.condarc
          conda version : 24.1.2
    conda-build version : 24.1.2
         python version : 3.11.7.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=m1
                          __conda=24.1.2=0
                          __osx=14.4.1=0
                          __unix=0=0
       base environment : /opt/anaconda3  (writable)
      conda av data dir : /opt/anaconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-arm64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-arm64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/anaconda3/pkgs
                          /Users/serdarkaracay/.conda/pkgs
       envs directories : /opt/anaconda3/envs
                          /Users/serdarkaracay/.conda/envs
               platform : osx-arm64
             user-agent : conda/24.1.2 requests/2.31.0 CPython/3.11.7 Darwin/23.4.0 OSX/14.4.1 solver/libmamba conda-libmamba-solver/24.1.0 libmambapy/1.5.6 aau/0.4.3 c/QkeNtkUrgwz7nVYVSzIrAg s/5f_5979BIZ-G0e4oRXaKzg e/ATRt1h_Xl4cCAzCR1M6zcQ
                UID:GID : 501:20
             netrc file : None
           offline mode : False
``` 

MacOS M1 Max Sonoma 14.4.1
Python 3.9.19

**Comment by serdarkaracay** [comment]
Thanks @lyie28.
I tried on main path so:


``` shell

❯ ls -ll
total 8
drwxr-xr-x  22 serdarkaracay  staff   704  3 Apr 23:24 LaVague
drwxr-xr-x  23 serdarkaracay  staff   736  3 Apr 23:23 chrome-linux64
drwxr-xr-x   4 serdarkaracay  staff   128  3 Apr 23:23 chromedriver-linux64
-rw-r--r--   1 serdarkaracay  staff  1236  3 Apr 23:18 setup.sh
(LaVague) 

❯ lavague-launch --file_path hf.txt  --config_path openai.py         
Traceback (most recent call last):
  File "/opt/anaconda3/envs/LaVague/bin/lavague-launch", line 8, in <module>
    sys.exit(launch())
  File "/Users/serdarkaracay/LaVague/LaVague/src/lavague/__init__.py", line 139, in launch
    action_engine, get_driver = load_action_engine(config_path)
  File "/Users/serdarkaracay/LaVague/LaVague/src/lavague/utils.py", line 31, in load_action_engine
    config_module = import_from_path(path)
  File "/Users/serdarkaracay/LaVague/LaVague/src/lavague/utils.py", line 24, in import_from_path
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 982, in get_code
  File "<frozen importlib._bootstrap_external>", line 1039, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'openai.py'
(LaVague) 
```




LaVague path 

``` shell
ls -ll       
total 104
-rw-r--r--   1 serdarkaracay  staff  11357  3 Apr 23:24 LICENSE
-rw-r--r--   1 serdarkaracay  staff   5425  3 Apr 23:24 README.md
-rw-r--r--   1 serdarkaracay  staff   5398  3 Apr 23:24 contributing.md
drwxr-xr-x   5 serdarkaracay  staff    160  3 Apr 23:24 docker
drwxr-xr-x  11 serdarkaracay  staff    352  3 Apr 23:24 docs
drwxr-xr-x   4 serdarkaracay  staff    128  3 Apr 23:24 examples
-rw-r--r--   1 serdarkaracay  staff   1121  3 Apr 23:24 install-dependencies.sh
drwxr-xr-x   7 serdarkaracay  staff    224  3 Apr 23:24 lavague-files
-rw-r--r--   1 serdarkaracay  staff   3015  3 Apr 23:24 mkdocs.yml
-rw-r--r--   1 serdarkaracay  staff   5494  3 Apr 23:24 prompt_template.txt
-rw-r--r--   1 serdarkaracay  staff   2374  3 Apr 23:24 pyproject.toml
-rw-r--r--   1 serdarkaracay  staff   1236  3 Apr 23:24 setup.sh
drwxr-xr-x   4 serdarkaracay  staff    128  3 Apr 23:24 src
drwxr-xr-x   5 serdarkaracay  staff    160  3 Apr 23:24 static
drwxr-xr-x   3 serdarkaracay  staff     96  3 Apr 23:24 tests

❯ lavague-launch --file_path hf.txt  --config_path openai.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/LaVague/bin/lavague-launch", line 8, in <module>
    sys.exit(launch())
  File "/Users/serdarkaracay/LaVague/LaVague/src/lavague/__init__.py", line 139, in launch
    action_engine, get_driver = load_action_engine(config_path)
  File "/Users/serdarkaracay/LaVague/LaVague/src/lavague/utils.py", line 31, in load_action_engine
    config_module = import_from_path(path)
  File "/Users/serdarkaracay/LaVague/LaVague/src/lavague/utils.py", line 24, in import_from_path
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 982, in get_code
  File "<frozen importlib._bootstrap_external>", line 1039, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'openai.py'
(LaVague) 

```

**Comment by shubhamofbce** [comment]
@lyie28 We changed the filename recently from `openai.py --> openai_api.py`, so we need to update the docs as well https://docs.lavague.ai/en/latest/docs/integrations/openai/

**Comment by lyie28** [comment]
I think this one is solved now. Feel free to re-open if you are still having issues
